# Generated by Django 3.1 on 2021-11-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=55, unique=True)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('status', models.CharField(choices=[('in stock', 'In stock'), ('out of stock', 'Out of stock'), ('awating', 'Awating')], max_length=23)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.category')),
            ],
        ),
    ]
